import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import Script from 'next/script'
const inter = Inter({ subsets: ['latin'] })
import { Toaster } from 'sonner';
import QueryProvider from '@/components/QueryProvider'
import SessionWrapper from '@/components/auth/sessionprovider'
import Nav from '@/components/nav'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <SessionWrapper>
    <html lang="en">
      <body className={inter.className}>
      <QueryProvider>
        <Nav/>
       
        
        {children}

        <Toaster
         position='top-center'
         richColors={true}
         closeButton={true}
        />
        </QueryProvider>
        </body>
    </html>
    </SessionWrapper>
  )
}
